boardmeets/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("license-body/", views.license_list, name="license_body"),
    path("current-users/", views.current_users, name="current_users"),
    path("license-body/add-license/", views.add_license, name='add_license'),
    path("license-body/edit-license/<int:license_id>", views.edit_license, name='edit_license'),
    path("license-body/delete-license/<int:license_id>", views.delete_license, name='delete_license'),
    path("current-users/edit-users/<int:license_id>", views.edit_currentusers_license, name='edit_currentusers'),
    path("current-users/delete-users/<int:license_id>", views.delete_currentusers_license, name='delete_currentusers'),



    path("organizations/", views.organization_list, name='organizations_list'),
    path("organizations/add", views.add_organization, name='add_organization'),
    path("organizations/<int:pk>/", views.organization_detail, name='organization_detail'),
    path("organizations/<int:pk>/edit/", views.edit_organization, name="edit_organization"),
    path("organizations/<int:pk>/delete/", views.delete_organization, name='delete_organization'),
    path("organizations/socials", views.organizations_socials, name='organizations_socials'),
    path("organizations/socials/<int:organization_id>/edit", views.edit_socials, name='edit_socials'),
    path("organization-names/", views.organizations_names, name='organization_names'),
    path("organization-leaders/<int:organization_id>/", views.organization_leaders, name='organization_leaders'),
    path("organization-leaders/<int:organization_id>/<int:leader_id>/edit/", views.edit_leader, name='edit_leader'),
    path("organization-leaders/<int:organization_id>/<int:leader_id>/delete", views.delete_leader, name='delete_leader'),
    path("organization-leaders/<int:organization_id>/add", views.add_leader, name='add_leader'),
    path("organizations-contacts/", views.organizations_contacts, name='organizations_contacts'),
    path("organizations-contacts/<int:organization_id>/add/", views.add_contact, name='add_contact'),
    path("organizations-contacts/<int:organization_id>/edit/", views.edit_contact, name='edit_contact'),
    path("organizations-contacts/<int:organization_id>/delete/", views.delete_contact, name='delete_contact'),
    # path("organizations-contacts/<int:organization_id>/", views.contacts, name='contacts'),
    
    # path("organization-leaders/<int:organization_id>/<int:leader_id>/edit/", views.edit_leader, name='edit_leader'),
    
]

boardmeets/boardmeets/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("base.urls")), # if i add '/base' i have to go to the route 127.0.0.1:8000 to see this page
]

boardmeets/base/models.py
from django.db import models
import uuid

# Create your models here.
class Organization(models.Model):
    id = models.AutoField(primary_key=True)
    organization_name = models.CharField(max_length=200)
    description = models.CharField(max_length=1000, default=None)
    location = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=200)
    website = models.CharField(max_length=200)
    stuff_number = models.IntegerField(null=True, blank=True)
    address = models.CharField(max_length=255, default=None)
    industry = models.CharField(max_length=255, default=None)
    is_nonprofit = models.BooleanField(default=False)
    established_date = models.DateField(default=None)
    social_media_facebook = models.URLField(null=True, blank=True)
    social_media_twitter = models.URLField(null=True, blank=True)
    social_media_instagram = models.URLField(null=True, blank=True)
    social_media_linkedin = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.organization_name
    
class Leader(models.Model):
    id = models.AutoField(primary_key=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    email = models.CharField(max_length=150)
    contact = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name

class License(models.Model):
    id = models.AutoField(primary_key=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    license_key = models.CharField(max_length=100)
    server_id = models.CharField(max_length=150)
    mac_address = models.CharField(max_length=200)
    license_type = models.CharField(max_length=150)
    license_expiry_date = models.DateField(default=True)
    number_of_users = models.IntegerField(default=0)
    is_active = models.BooleanField(default=False)

boardmeets/base/forms.py
from django import forms
from .models import Organization, Leader, License

class OrganizationForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = '__all__'

class LeaderForm(forms.ModelForm):
    class Meta:
        model = Leader
        fields = ['name', 'title', 'email', 'contact']

class ContactForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = ['phone_number']

class SocialForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = ['social_media_facebook', 'social_media_instagram', 'social_media_linkedin', 'social_media_twitter']

class LicenseForm(forms.ModelForm):
    class Meta:
        model = License
        fields = '__all__'
        widgets = {
            'description': forms.Textarea(attrs={'class': 'custom-form-control'}),
        }

class CurrentUsersLicenseForm(forms.ModelForm):
    class Meta:
        model = License
        fields = ['organization', 'license_key', 'number_of_users']

boardmeets/base/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Organization, Leader, License
from .forms import OrganizationForm, LeaderForm, ContactForm, SocialForm, LicenseForm, CurrentUsersLicenseForm

# ORGANIZATIONS VIEW FUNCTIONS
# Create your views here.
def index(request):
    return render(request, 'base/home.html')
    # return HttpResponse("Hello There. You are at the Board Meets Landing Page")

def organization_list(request):
    organizations = Organization.objects.all()
    context = {'organizations': organizations}
    return render(request, 'base/organizations_list.html', context)
    # return render(request, 'base/organizations_list.html')

#Counts the number of organizations in Organizations Model
def organization_number(request):
    organizations = Organization.objects.all()
    organizations_count = organizations.count()
    return render(request, 'base/home.html', {'organizations_count': organizations_count})

# Logic for displaying organizations details
def organization_detail(request, pk):
    organization = get_object_or_404(Organization, pk=pk)
    return render(request, 'base/organization_detail.html', {'organization': organization})

# Adding an Organization
def add_organization(request):
    if request.method == "POST":
        form = OrganizationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('organizations_list')
    else:
        form = OrganizationForm()
    return render(request, 'base/add_organization.html', {'form': form})
        
#Editing Organization Details
def edit_organization(request, pk):
    organization = get_object_or_404(Organization, pk=pk)

    if request.method == "POST":
        form = OrganizationForm(request.POST, instance=organization)
        if form.is_valid():
            form.save()
            return redirect('organization_detail', pk=organization.pk)
    else:
        form = OrganizationForm(instance=organization)
    return render(request, 'base/edit_organization.html', {'form': form})

# DEleting An Organization from the Model
def delete_organization(request, pk):
    organization = get_object_or_404(Organization, pk=pk)

    if request.method == "POST":
        organization.delete()
        return redirect('organizations_list')
    return render(request, 'base/delete_organization.html', {'organization': organization})


# ORGANIZATIONS_SOCIAL VIEW FUNCTIONS
def organizations_socials(request):
    organizations = Organization.objects.all()
    context = {'organizations': organizations}
    return render(request, 'base/organizations_socials.html', context)

#Edit Socials
def edit_socials(request, organization_id):
    organization = get_object_or_404(Organization, id=organization_id)

    if request.method == "POST":
        form = SocialForm(request.POST, instance=organization)
        if form.is_valid():
            organization = form.save()
            return redirect('organizations_socials')
    else:
        form = SocialForm(instance=organization)
    return render(request, 'base/edit_socials.html', {'form': form, 'organization': organization})


# LEADER : ORGANIZATIONS_LEADERS
def organizations_names(request):
    organizations = Organization.objects.all()
    context = {'organizations': organizations}
    return render(request, 'base/organization_names.html', context)


def organization_leaders(request, organization_id):
    organization = get_object_or_404(Organization, id=organization_id)
    organization_leaders = Leader.objects.filter(organization=organization)

    context = {
        'organization': organization,
        'leaders': organization_leaders
    }

    return render(request, 'base/organization_leaders.html', context)

#editing a leader
def edit_leader(request, organization_id, leader_id):
    leader = get_object_or_404(Leader, id=leader_id)

    if request.method == "POST":
        form = LeaderForm(request.POST, instance=leader)
        if form.is_valid():
            form.save()
            # Redirect to the leaders page
            return redirect('organization_leaders', organization_id=organization_id)
    else:
        form = LeaderForm(instance=leader)

    return render(request, 'base/edit_leader.html', {'form': form, 'leader': leader})

def delete_leader(request, organization_id, leader_id):
    leader = get_object_or_404(Leader, id=leader_id)

    if request.method == "POST":
        leader.delete()
        #Redirect
        return redirect('organization_leaders', organization_id=organization_id)
    return render(request, 'base/delete_leader.html', {'leader': leader, 'organization_id': organization_id})

#Add a new leader
def add_leader(request, organization_id):
    if request.method == "POST":
        form = LeaderForm(request.POST)
        if form.is_valid():
            leader = form.save(commit = False)
            leader.organization_id = organization_id
            leader.save()
            return redirect('organization_leaders', organization_id=organization_id)
    else:
        form = LeaderForm()

    return render(request, 'base/add_leader.html', {'form': form, 'organization_id': organization_id})


# ORGANIZATION CONTACTS
# A list of all organizations 

def organizations_contacts(request):
    organizations = Organization.objects.all()
    context = {'organizations': organizations}
    return render(request, 'base/organization_contacts.html', context)

# Adds a new contact on the contacts list
def add_contact(request, organization_id):
    organization = get_object_or_404(Organization, id=organization_id)

    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            new_contact = form.cleaned_data.get('phone_number')
            existing_contacts = organization.phone_number
            if existing_contacts:
                organization.phone_number = f"{existing_contacts}, {new_contact}"
            else:
                organization.phone_number = new_contact
            organization.save()
            return redirect('organizations_contacts')
    else:
        form = ContactForm()

    return render(request, 'base/add_contact.html', {'form': form, 'organization': organization})


def edit_contact(request, organization_id):
    organization = get_object_or_404(Organization, id=organization_id)

    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.cleaned_data.get('phone_number')
            organization.phone_number = contact
            organization.save()
            return redirect('organizations_contacts')
    else:
        form = ContactForm(instance=organization)

    return render(request, 'base/edit_contact.html', {'form': form, 'organization': organization})

from django.contrib import messages

def delete_contact(request, organization_id):
    organization = get_object_or_404(Organization, id=organization_id)

    if request.method == "POST":
        contact_to_delete = request.POST.get('contact')
        existing_contacts = organization.phone_number

        if existing_contacts and contact_to_delete in existing_contacts:
            # Remove the contact from the existing contacts
            updated_contacts = existing_contacts.replace(contact_to_delete, '').strip(', ')
            organization.phone_number = updated_contacts
            organization.save()
            messages.success(request, 'Contact deleted successfully.')

    return redirect('organizations_contacts')

# LICENSE
def license_list(request):
    licenses = License.objects.all()
    return render(request, 'base/license_list.html', {'licenses': licenses})

def current_users(request):
    licenses = License.objects.all()
    return render(request, 'base/current_users.html', {'licenses':licenses})

#Adding a license
def add_license(request):
   
    if request.method == 'POST':
        form = LicenseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('license_body')
    else:
        form = LicenseForm()

    context = {'form': form}
    return render(request, 'base/add_license.html', context)

def edit_license(request, license_id):
    license = get_object_or_404(License, id=license_id)
    if request.method =='POST':
        form = LicenseForm(request.POST, instance=license)
        if form.is_valid():
            form.save()
            # Redirect to the license page
            return redirect('license_body')
    else:
        form = LicenseForm(instance=license)

    return render(request, 'base/edit_license.html', {'form': form, 'license': license})


def delete_license(request, license_id):
    license = get_object_or_404(License, id=license_id)
    if request.method == "POST":
        license.delete()
        # Redirect
        return redirect('license_body')
    return render(request, 'base/delete_license.html', {'license': license})
    

#CURRENT USER
# Retrives a list of Current Users
def currentuser_list (request):
    licenses = License.objects.all()

    #Extract the required data from each license object
    organizations = [license.organization for license in licenses]
    license_keys = [license.license_key for license in licenses]
    number_of_users = [license.number_of_users for license in licenses]

    #Pass the data to the template for rendering
    context = {
        'organizations': organizations,
        'license_keys': license_keys,
        'number_of_users': number_of_users,
    }
    
    return render(request, 'base/edit_currentusers.html', context)

def edit_currentusers_license(request, license_id):
    license = get_object_or_404(License, id=license_id)
    if request.method =='POST':
        form = CurrentUsersLicenseForm(request.POST, instance=license)
        if form.is_valid():
            form.save()
            # Redirect to the license page
            return redirect('current_users')
    else:

boardmeets/base/templates/base/add_license.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add License</title>

    <!-- LOADING CSS FILE -->
    <link rel="stylesheet" href="{% static '/css/main.css' %}" type="text/css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

    <!-- FONT AWESOME LIBRARY -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
</head>
<body>
<nav class="navbar navbar-color">
    <div class="container-fluid d-flex align-items-center">
        <img class="logo-image" src="{% static '/images/logo.jpg' %}" alt="logo">
        <a class="navbar-brand d-flex mx-auto" href="#">
            <h2 class="mb-0">LICENSE TOOL</h2>
        </a>
    </div>
</nav>

<div class="container">
    <div class="row shadow mt-5">
        <div class="col-md-8 offset-md-2">
            <div class="form-container">
                <h1 class="form-title text-center">Add License</h1>
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="{{ form.organization.id_for_label }}" class="form-label">Organization</label>
                        {{ form.organization }}
                        {% if form.organization.errors %}
                            {% for error in form.organization.errors %}
                                <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        <label for="{{ form.license_key.id_for_label }}" class="form-label">License Key</label>
                        {{ form.license_key }}
                        {% if form.license_key.errors %}
                            {% for error in form.license_key.errors %}
                                <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        <label for="{{ form.server_id.id_for_label }}" class="form-label">Server ID</label>
                        {{ form.server_id }}
                        {% if form.server_id.errors %}
                            {% for error in form.server_id.errors %}
                                <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        <label for="{{ form.mac_address.id_for_label }}" class="form-label">Mac Address</label>
                        {{ form.mac_address }}
                        {% if form.mac_address.errors %}
                            {% for error in form.mac_address.errors %}
                                <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        <label for="{{ form.license_type.id_for_label }}" class="form-label">License Type</label>
                        {{ form.license_type }}
                        {% if form.license_type.errors %}
                            {% for error in form.license_type.errors %}
                                <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        <label for="{{ form.license_expiry_date.id_for_label }}" class="form-label">License Expiry Date</label>
                        {{ form.license_expiry_date }}
                        {% if form.license_expiry_date.errors %}
                            {% for error in form.license_expiry_date.errors %}
                                <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        <label for="{{ form.number_of_users.id_for_label }}" class="form-label">Number of Users</label>
                        {{ form.number_of_users }}
                        {% if form.number_of_users.errors %}
                            {% for error in form.number_of_users.errors %}
                                <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        <label for="{{ form.is_active.id_for_label }}" class="form-label">Is Active</label>
                        {{ form.is_active }}
                        {% if form.is_active.errors %}
                            {% for error in form.is_active.errors %}
                                <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <div class="text-center mt-3 mb-4 equal-width-btns">
                        <button type="submit" class="btn btn-outline-success btn-md">Add</button>
                        <a href="{% url 'license_body' %}" class="btn btn-outline-secondary btn-md">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- FOOTER -->
<footer class="home-footer text-white p-4 fixed-bottom">
    <div class="d-flex justify-content-center align-items-center">
        <span class="me-3" style="font-size: 18px;">
            <i class="fas fa-user"></i> Users
        </span>
        <span class="ms-3" style="font-size: 18px;">
            <i class="fas fa-users"></i> Groups
        </span>
    </div>
</footer>

<!-- JavaScript dependencies -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

boardmeets/base/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>License Tool</title>

    <!-- LOADING CSS FILE -->
    <link rel="stylesheet" href="{% static '/css/main.css' %}" type="text/css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

    <!-- FONT AWESOME LIBRARY -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
    <!-- NAVIGATION BAR -->
    <nav class="navbar navbar-color">
        <div class="container-fluid d-flex align-items-center">
            <img class="logo-image" src="{% static '/images/logo.jpg' %}" alt="logo">
            <a class="navbar-brand d-flex mx-auto" href="#">
                <h2 class="mb-0">LICENCE TOOL</h2>
            </a>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
    <!-- FOOTER -->
    <footer class="home-footer text-white p-3 fixed-bottom">
        <div class="d-flex justify-content-center align-items-center">
            <span class="me-3" style="font-size: 18px;">
            <i class="fas fa-user"></i> Users
            </span>
            <span class="ms-3" style="font-size: 18px;">
            <i class="fas fa-users"></i> Groups
            </span>
        </div>
    </footer>

    <!-- Bootstrap Javascript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

boardmeets/base/templates/base/current_users.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- LOADING CSS FILE -->
    <link rel="stylesheet" href="{% static '/css/main.css' %}" type="text/css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

    <!-- FONT AWESOME LIBRARY -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <title>License List</title>
    <style>
        body {
            padding-bottom: 90px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-color">
        <div class="container-fluid d-flex align-items-center">
            <img class="logo-image" src="{% static '/images/logo.jpg' %}" alt="logo">
            <a class="navbar-brand d-flex mx-auto" href="#">
                <h2 class="mb-0">CURRENT USERS</h2>
            </a>
        </div>
    </nav>

    <div class="container">
        <h1 class="text-center mt-4 mb-4 ">Current Users List</h1>
        <hr>
        <div class="equal-width-btns">
            <a href="{% url 'index' %}" class="btn btn-outline-secondary mb-3">Back</a>
            <a href="{% url 'add_license' %}" class="btn btn-outline-warning mb-3">Add</a>
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Index</th>
                    <th scope="col">organizations</th>
                    <th scope="col">License key</th>
                    <th scope="col">No of users</th>
                    <th scope="col">No of active users</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for license in licenses %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ license.organization }}</td>
                        <td>{{ license.license_key }}</td>
                        <td>{{ license.number_of_users }}</td>
                        <td>{{ license.number_of_users }}</td>
                        <td class="equal-width-btns">
                            <a href="{% url 'edit_currentusers' license.id %}" class="btn btn-outline-success btn-sm">Edit</a>
                            <a href="{% url 'delete_currentusers' license.id %}" class="btn btn-outline-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3">No licenses found.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- FOOTER -->
    <footer class="home-footer text-white p-3 fixed-bottom">
        <div class="d-flex justify-content-center align-items-center">
            <span class="me-3" style="font-size: 18px;">
            <i class="fas fa-user"></i> Users
            </span>
            <span class="ms-3" style="font-size: 18px;">
            <i class="fas fa-users"></i> Groups
            </span>
        </div>
    </footer>

    <!-- Bootstrap Javascript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    
</body>
</html>

boardmeets/base/templates/base/edit_leader.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <title>Edit Leader</title>
    <!-- LOADING CSS FILE -->
    <link rel="stylesheet" href="{% static '/css/main.css' %}" type="text/css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

    <!-- FONT AWESOME LIBRARY -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <style>
        body {
            background-color: #f8f9fa;
        }
        .container {
            max-width: 500px;
            margin: 0 auto;
            padding-top: 100px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-color">
        <div class="container-fluid d-flex align-items-center">
            <img class="logo-image" src="{% static '/images/logo.jpg' %}" alt="logo">
            <a class="navbar-brand d-flex mx-auto" href="#">
                <h2 class="mb-0">Leaders</h2>
            </a>
        </div>
    </nav>

    <div class="container">
        <h1 class="text-center mb-4">Edit Leader</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_name" class="form-label">Name: </label>
                {{ form.name }}
            </div>
            <div class="mb-3">
                <label for="id_position" class="form-label">Position: </label>
                {{ form.title }}
            </div>
            <div class="mb-3">
                <label for="id_email" class="form-label">Email: </label>
                {{ form.email }}
            </div>
            <div class="mb-3">
                <label for="id_email" class="form-label">Contact: </label>
                {{ form.contact }}
            </div>
            <div class="equal-width-btns">
                <button type="submit" class="btn btn-outline-success">Save </button>
                <a href=""class="btn btn-outline-secondary">Cancel</a>
            </div>
            
            
        </form>
    </div>

    <!-- FOOTER -->
    <footer class="home-footer text-white p-4 fixed-bottom">
        <div class="d-flex justify-content-center align-items-center">
            <span class="me-3" style="font-size: 18px;">
            <i class="fas fa-user"></i> Users
            </span>
            <span class="ms-3" style="font-size: 18px;">
            <i class="fas fa-users"></i> Groups
            </span>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>